# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Weekly Summary

on:
  release:
    types: [commit]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Run summary
      run:  git log --since="one week ago" --pretty=oneline
    
